### ISSUE TITLE
the question about  editing

### ISSUE THREAD

**Issue by minhang-chen** [baixiaoji/Express-note#1]
I can edit other people's content

**Comment by baixiaoji** [comment]
@minhang-chen     you can using the  chinese.(你可以用中文的)

还有是在那里的模块可以结束上传说明要仔细，谢谢

**Comment by baixiaoji** [comment]
@minhang-chen     you can using the  chinese.(你可以用中文的)

还有是在那里的模块可以结束上传说明要仔细，谢谢

**Comment by baixiaoji** [comment]
查看过后是，发现登录过后回到广场的时候可以去修改别人的留言，显示的提示是修改成功，但是不会录入数据库，所以这里可能提示的信息没有完善起来。

**Comment by baixiaoji** [comment]
查看过后是，发现登录过后回到广场的时候可以去修改别人的留言，显示的提示是修改成功，但是不会录入数据库，所以这里可能提示的信息没有完善起来。

**Comment by baixiaoji** [comment]
查看过后是，发现登录过后回到广场的时候可以去修改别人的留言，显示的提示是修改成功，但是不会录入数据库，所以这里可能提示的信息没有完善起来。

**Comment by minhang-chen** [comment]
plase speak english

**Comment by baixiaoji** [comment]
fixed,Thx. Waitting for next version
